services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_User: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: itp4915m_se1d_group4
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - itp4915m

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mariadb
    networks:
      - itp4915m

networks:
  itp4915m:
    name: itp4915m_1D_group4
