version: '3.9'

services:
  #  nginx:  # comment this out if you don't want to use nginx
  #    image: nginx:1.21.6
  #    ports:
  #      - "80:80"
  #    volumes:
  #      - ./resources/docker/nginx/:/etc/nginx/
  #      - ./:/var/www/html
  #    depends_on:
  #      - mkdocs
  mkdocs:
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    command: serve -a 0.0.0.0:8000
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_User: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: itp4915m_se1d_group4
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mariadb

networks:
  default:
    name: itp4915m_se1d_group4_network
