version: '3.9'

services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_User: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: itp4915m_se1d_group4
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mariadb

networks:
  default:
    name: itp4915m_se1d_group4_network
