services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: itp4915m_se1d_group4
    ports:
      - "5432:5432"
    networks:
      - pg_network

  phppgadmin:
    image: dockage/phppgadmin
    restart: always
    environment:
      PHP_PG_ADMIN_SERVER_HOSTS: db
      PHP_PG_ADMIN_SERVER_PORTS: 5432
    ports:
      - "8080:80"
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge